### ISSUE TITLE
The scrutinizer stucks on "Waiting for External Code Coverage"

### ISSUE THREAD

**Issue by chyzas** [ongr-io/ongr-sandbox#54]
Maybe the problem is in these lines:
```
application:
  project_setup:
    before:
      - composer install --prefer-source
```
